### ISSUE TITLE
E-CAD für PCB

### ISSUE THREAD

**Issue by daniw** [pren-et/stepper#2]
Welches Tool wollen wir verwenden um Platinen zu erstellen? 

Vorschläge: 
- KiCad
- Eagle
- Altium Designer

Betty: Du hast mal was erwähnt, dass du gerne mit Altium Designer arbeiten würdest. 

Bevor diese Frage geklärt ist, sollten noch keine Bibliotheken für Bauteile usw. angelegt werden. 

Ich kann mit allen Varianten oben leben.

**Comment by BettyET** [comment]
Ja, ich kenne nur Altium Designer, und da das das Tool ist, welches man an der Schule auch lernt, bin ich sehr dafür.

**Comment by Flavinsky** [comment]
Für mich ist der Altium Designer auch I.O
Ich habe die woche vom 9.2.15 sonst zeit ein paar tage an der hslu zu arbeiten. Nächste woche evt. Am Do und Fr.

**Comment by daniw** [comment]
Also verwenden wir Altium Designer

**Comment by daniw** [comment]
Beim BLDC Motor Treiber wird Altium Designer verwendet: 
pren-et/bldc#5
